### PR TITLE
Fix depwarn in test

### PR DESCRIPTION
**Pull request by ranjanan**
cs -> levels(cs)

### CODE REVIEW

**Comment by ranjanan** [comment]
Ah I see, I didn't know it was _meant_ to throw a depwarn. Thanks!

**Comment by tlycken** [comment]
Well, no - because that test is removed on the latest master :P

If you do `Pkg.checkout("Contour")` to get it, you won't see that warning anymore.

**Comment by ranjanan** [comment]
Cool, you're right. 😄  Would you mind tagging a new release then? Or do you want to wait on that?

**Comment by tlycken** [comment]
I'm working on it: https://github.com/JuliaLang/METADATA.jl/pull/5901

**Pull request closed without merging**
